export const BOOKING_ROOM_REQUEST = 'BOOKING_ROOM_REQUEST';
export const BOOKING_ROOM_SUCCESS = 'BOOKING_ROOM_SUCCESS';
export const BOOKING_ROOM_FAIL = 'BOOKING_ROOM_FAIL';
export const GET_BOOKING_REQUEST = 'GET_BOOKING_REQUEST';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAIL = 'GET_BOOKING_FAIL';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
